name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up the date and time
      run: |
        sudo apt-get update
        sudo apt-get install -y tzdata
        sudo ln -fs /usr/share/zoneinfo/America/Fortaleza /etc/localtime
        sudo dpkg-reconfigure --frontend noninteractive tzdata

    - name: Run Bash script to update README
      run: |
        chmod +x update_readme.sh
        sudo ./update_readme.sh

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git stash --include-untracked
        git pull origin main --rebase
        git stash pop
        git add README.md
        git commit -m "Update README"
        git push
